### ISSUE TITLE
Update style of JuliaFormatter to mix with TulipaEnergyModel's style

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/COPIERTemplate.jl#90]
This is what is in there right now:

```toml
align_assignment = true
align_matrix = true
align_pair_arrow = true
align_struct_field = true
always_for_in = true
conditional_to_if = true
for_in_replacement = "in"
format_docstrings = false
format_markdown = false
import_to_using = true
indent = 4
margin = 100
normalize_line_endings = "unix"
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
verbose = true
```
